# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'IDAP-OOP' do

  target 'IDAP-OOPTests' do
    testing_pods
  end

  target 'IDAP-OOPUITests' do
    testing_pods
  end

end
